url: https://postgresqlstan.github.io
title: CLI Notes
description: >- # this means to ignore newlines until "baseurl:"
  "Links, notes, tips, and articles about various command line interface tools, but mainly PostgreSQL"
twitter_username: "PostgreSqlStan"
github_username: "PostgreSqlStan"
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 8 # amount of posts to show
paginate_path: /page:num/
timezone: America/Chicago

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "PostgreSQL Stan"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : ":elephant: postgres fanatic<br>:hammer: command line aficionado<br>:zap: macOS/darwin (Unix) user"
  location: "Tulsa, OK"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/postgresqlstan"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/postgresqlstan"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/postgresqlstan"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/postgresqlstan"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


logo: "assets/images/logo.jpg"
repository: "PostgreSqlStan/postgresqlstan.github.io"
date_format: "%Y-%m-%d"
exclude:
  - README.md
  - LICENSE

# show_drafts: true
